### ISSUE TITLE
Is it possible to style for dark mode?

### ISSUE THREAD

**Issue by jeanmw** [splitbee/react-notion#115]
Is it possible to use custom styles like dark mode ?
I'm using tailwind, but I've tried using a `style` property as well.
```
import React from 'react';
import PropTypes from 'prop-types';
import { css, styled } from 'twin.macro';

const styles = css`
.dark-mode {
  .notion, .notion-text, .notion-page-link {
    color: white;
  }
}`;

const StyledDiv = styled.div(() => [styles]);
...
  return (
<StyledDiv>
    <NotionRenderer blockMap={recordMap.data} />
</StyedDiv>
  );
```
This doesn't seem to work:

<img width="1110" alt="Screen Shot 2023-03-07 at 4 10 07 PM" src="https://user-images.githubusercontent.com/11809238/223585056-0e87b692-a657-4166-a4f5-1a8240d07650.png">

Is there an alternative besides forking this repo and fixing the styles in the fork?

**Comment by nishantb06** [comment]
hi, facing the same issue , how were you able to solve it ? 
was a new feature implemented in this library for this ?
