### ISSUE TITLE
BookmarkValueType may not include format.

### ISSUE THREAD

**Issue by saitoukun** [splitbee/react-notion#18]
BookmarkValueType may not include format.
You'll get the following error.
<img width="656" alt="スクリーンショット 2020-07-07 10 56 06" src="https://user-images.githubusercontent.com/38334778/86687800-7e710f00-c040-11ea-9e69-0de001304921.png">

**Comment by transitive-bullshit** [comment]
Hey @saitoukun, would you mind including a link to a public notion page that reproduces the issue?

Thanks 😄

**Comment by saitoukun** [comment]
👍 
https://www.notion.so/test-40eb0e26e9b7429dbadeb6f0eb39da66
