### ISSUE TITLE
Full support for collection views

### ISSUE THREAD

**Issue by transitive-bullshit** [splitbee/react-notion#23]
Let's track progress in this issue. Higher priority items listed first.

Note that none of these items have been merged or released yet.

- [x] table view
- [x] gallery view
- [x] list view
- [x] board view
- [ ] calendar view
- [x] formula support
- [x] ability to switch views
- [ ] lazy loading for larger collections (e.g. [pokedex](https://www.notion.so/saasifysh/Notion-Pok-dex-51870ff555ce43ef857d4c5e6b8caad6))
- [x] ability to search / filter views
- [x] ability to sort views

**Comment by transitive-bullshit** [comment]
I found a solid WIP implementation [here](https://github.com/tugboatcoding/react-potion/blob/master/src/components/Collection.js) by @logicalicy.

Here's what his version currently looks like:

![Screen Shot 2020-07-22 at 6 51 02 AM](https://user-images.githubusercontent.com/552829/88168394-5bba2b00-cbe8-11ea-8539-9a0d29d35daa.jpg)

@logicalicy would you be open to joining a zoom call at some point to discuss collaborating and share knowledge?

**Comment by tobiaslins** [comment]
Looks cool!

I think supporting all types of views would be cool and also switching between them. Filtering/search+ sorting is a nice to have

**Comment by transitive-bullshit** [comment]
Here's a kitchen sink type test page for table views: https://www.notion.so/saasifysh/Collection-Tests-2fea615a97a7401c81be486e4eec2e94

**Comment by logicalicy** [comment]
> @logicalicy would you be open to joining a zoom call at some point to discuss collaborating and share knowledge?

Hey @transitive-bullshit I haven't been advertising the project so very cool that you've found it! Happy to join a zoom, sure. Feel free to DM me on Twitter (same handle)

**Comment by transitive-bullshit** [comment]
Awesome - it looks like your twitter DMs aren't open to the public, so would you mind pinging me on this open slack workspace? https://slack.saasify.sh

Tobias and Timo are also on there in the #react-notion channel, so it could be useful to discuss things going forwards.

**Comment by logicalicy** [comment]
@transitive-bullshit Sorry I seem to have had DMs switched off. I was struggling to join the Slack workspace so feel free to DM me

**Comment by logicalicy** [comment]
> in the `#react-notion` channel

Have joined!

**Comment by transitive-bullshit** [comment]
## Update

I've added support for 95% of collection views, but it required a *lot* of changes.

I've also refactored the Notion API and types into their own, isolated packages, `notion-client` and `notion-types` which you can find here: https://github.com/saasify-sh/notion-kit

Note that this also required a large amount of changes to get collection views, embeds, and other features working properly.

One of the main changes is instead of changing the shape of the data that's returned from the API and injecting collection data into blocks, it's much, much easier to work with and debug these use cases if we retain the exact same structure as the original Notion API. So now `NotionRenderer` takes in an `ExtendedRecordMap` instead of a simple `BlockMap`.

## Demo

Here's a quick side-by-side [demo video](https://www.youtube.com/watch?v=_-bCwt-iy54) of the progress.

**Comment by lukebennett** [comment]
What's the latest on this? I can't see a branch anywhere, how would I have a play with it? If it's mostly there, what's the possibility of pushing an alpha package or something?

**Comment by transitive-bullshit** [comment]
@lukebennett you can check out a full working version of my fork at [react-notion-x](https://github.com/NotionX/react-notion-x).

Due to the large amount of changes needed to support collections as well as many other block types and fixes, I decided to release it as a separate project for now. My hope is that `react-notion` and `react-notion-x` can eventually be merged back together, but either way I wanted to get all the work I've done improving `react-notion` over the past few months back in the land of open source.

**Comment by lukebennett** [comment]
Aha great, thanks for making that available! I'd already migrated to `notion-client` so hopefully `react-notion-x` will slot right in alongside it - collections is one of the key things I need. I'll take a gander at #36 as well, would be great to consolidate everything back together.

**Comment by transitive-bullshit** [comment]
Yep; `react-notion-x` goes hand-in-hand with `notion-client`.
