### ISSUE TITLE
rendering issue with lists containing "details"

### ISSUE THREAD

**Issue by chrisdrackett** [splitbee/react-notion#39]
Given the following notion page:

https://www.notion.so/Test-Page-c09625d885ed406389be865b5e96e154

![CleanShot 2020-11-10 at 16 19 08@2x](https://user-images.githubusercontent.com/4378/98841038-69e0c100-23fc-11eb-8f69-bc62185fc78e.jpeg)

I'm getting the following output from react-notion:

![CleanShot 2020-11-10 at 16 18 28@2x](https://user-images.githubusercontent.com/4378/98841150-90066100-23fc-11eb-9b89-f128e5d705a7.jpeg)

It seems like react-notion is making more list items than notion is which causes excess nesting.

**Comment by transitive-bullshit** [comment]
Hey Chris, your images aren't loading correctly. You can upload them to GitHub directly by dragging them onto your post.

**Comment by chrisdrackett** [comment]
@transitive-bullshit ok, images updated
