### ISSUE TITLE
Numbered lists aren't working

### ISSUE THREAD

**Issue by kartiknair** [splitbee/react-notion#4]
Hey there thanks for creating this amazing project. I was building a blog using this and noticed that numbered lists weren't working correctly. I'm getting a new `<ol>` for each list item. Here's an example page that's causing the issue: https://www.notion.so/9c562515cbf444b5aa3c4270a67f5cce.

**Comment by kartiknair** [comment]
This is how it's looking:
![image](https://user-images.githubusercontent.com/49618293/82077957-5d033f00-96f1-11ea-87ff-1c1150997de9.png)

If you would like I could also create a codesandbox with the code as well.

**Comment by zephraph** [comment]
So, I've been digging into this and it's a bit tricky. The `NotionRenderer` is a recursive component... you give it the block map and it renders out the first block (initial the page) and the children of that block get the same treatment. 

With a flat page as you show here, there's the page which is the main block and all its content. Essentially, for what we care about, we're rendering a flat list of content here.

The challenges comes by how `NotionRenderer` renders each block. It iterates over the list, checks their type, and then renders that type. I think there's some base assumption here that things like lists would share a base block and that rendering that one block would render all its contents correctly. Unfortunately that's not the case. Every entry in a list is itself a new block. This somewhat makes sense considering the fact that a list entry could technically be... well... any other block? 

So the renderer is looping through the page contents and rendering each block by its type. It sees the `numbered_list` and it wraps that in an `ol`... then it sees another `numbered_list` and does the same. Therein lies the problem.

To really fix this it seems like the renderer can't just iterate through the blocks and render each on in turn. It needs to (at the very least) check for lists and group them in the correct `ol`s or `ul`s.

It's not necessarily the hardest thing, but not the easiest either. It'll make the rendering logic more complicated.

**Comment by kartiknair** [comment]
Hmmm I've been looking into it as well and it seems to be an issue at the API level. The reason bullet lists work fine is because in the API response you can see that a Bullet List block has a content property that holds its children. But numbered lists don't seem to have this content property which is why it's assuming every block is a new list. I don't know how you could solve this though.

**Comment by zephraph** [comment]
@kartiknair I've got a PR

**Comment by kartiknair** [comment]
@zephraph thanks for the quick work. I appreciate your help!

**Comment by timolins** [comment]
As correctly mentioned by @kartiknair, there are still some issues with top level lists.
