### ISSUE TITLE
Lists start over with each item

### ISSUE THREAD

**Issue by khrome83** [splitbee/react-notion#46]
For some reason, lists start over with each item is rendered.

So instead of -
```
<ul>
  <li>Item 1</li>
  <li>Item 2</li>
  <li>Item 3</li>
</ul>
```

It comes out as -
```
<ul>
  <li>Item 1</li>
</ul>
<ul>
  <li>Item 2</li>
</ul>
<ul>
  <li>Item 3</li>
</ul>
```

It has the correct notion classes and everything. But it always starts the list over.

**Comment by tobiaslins** [comment]
While this is true, does it give you render issues? We had to use this approach to support all edge cases (nested lists,..)

Please reopen this issue with a Notion document in case you have issues!
