### ISSUE TITLE
Underlined text not supported

### ISSUE THREAD

**Issue by iuzn** [splitbee/react-notion#48]
Since an underlined text doesn't have a tag in Notion, there is no tag on the API side.
Notion uses border instead of tags.
For this reason, Notion renderer cannot manipulate underlined texts.
**How can we find a solution to this? 
Is it necessary to make an improvement on the [API worker](https://github.com/splitbee/notion-api-worker) side?**

Notion page:
![image](https://user-images.githubusercontent.com/25708048/103159576-170c6e80-47dc-11eb-893c-94a788a77453.png)

Output:
![image](https://user-images.githubusercontent.com/25708048/103159580-225f9a00-47dc-11eb-8abf-81dc5102d0b5.png)

API worker:
![image](https://user-images.githubusercontent.com/25708048/103159559-fe03bd80-47db-11eb-9b77-cffa7354e39f.png)

**Comment by transitive-bullshit** [comment]
Hey @iuzn this is supported via https://github.com/NotionX/react-notion-x

**Comment by iuzn** [comment]
@transitive-bullshit I know, it's a good job. I will try this for another version of my project, until I code my own package.
