### ISSUE TITLE
Replace notion-api-worker with official Notion API?

### ISSUE THREAD

**Issue by FruitVodka** [splitbee/react-notion#66]
Hi,
The Notion API beta version is out now!
Wondering if that changes anything for this project? I haven't looked at it in detail yet but I wanted to make a portfolio website for myself that looked like and came from Notion and that's when I came across this - seems very cool 😮 .
If you want to add in [the JS SDK](https://github.com/makenotion/notion-sdk-js) for the official Notion API here, I'd like to contribute 😸 !

**Comment by danielfalbo** [comment]
Did you close this because you’ve successfully tried to use the official api with react-notion?

**Comment by tobiaslins** [comment]
@danielfalbo the official api block response is not supported by react-notion (yet?).
We're thinking about to move forward with their move. Maybe we'll build a more customizable v2 that bases on the public api!
