### ISSUE TITLE
Checkboxes do not render

### ISSUE THREAD

**Issue by plc** [splitbee/react-notion#86]
If you import a Notion page that includes checkboxes, the library will cause an error and not render.

Since the library has no way to actually write back the checkbox interaction back to Notion, I propose it simply reads if the checkbox is checked or not and render that (with no way of toggling it from the library) — so if a checkbox is un-checked, it will simply show an empty checkbox, and if it is checked, it will simply show a checked checkbox.

Proposed fix:
- [ ] Render checkboxes with their current state:
- [ ] If a Notion page has a checkbox that is un-checked, render an empty checkbox
- [ ] If a Notion page has a checkbox that is checked, render a checked checkbox.

**Comment by plc** [comment]
Hello, I made a bounty for this issue since we'd love to see it fixed :) https://gitpay.me/#/task/533

**Comment by pyk** [comment]
Btw for the checkbox, I think it is by design doesn't [support a checkbox](https://github.com/splitbee/react-notion/blob/master/README.md#supported-blocks). The author recommend to use react-notion-x

**Comment by grimalschi** [comment]
@pyk not sure, there is "Not planned" label only at databases line.

**Comment by timolins** [comment]
I did some experiments with the checkbox and it shouldn't be too hard to support. I'll let you know when there is something usable.

**Comment by 007tom** [comment]
@plc @timolins @pyk 

PTAL: https://github.com/splitbee/react-notion/pull/92
